// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_LUizDCVn_wkJdD11QyPzmmO2FEZPik',
    appId: '1:703908194362:web:30ec0ce73de4e19590ed03',
    messagingSenderId: '703908194362',
    projectId: 'ayiolo-safari',
    authDomain: 'ayiolo-safari.firebaseapp.com',
    storageBucket: 'ayiolo-safari.appspot.com',
    measurementId: 'G-VCXEF0Y1B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmECIIQDXeInCNf_Lf3X3FiI8wklvQsI',
    appId: '1:703908194362:android:2920540895a3847490ed03',
    messagingSenderId: '703908194362',
    projectId: 'ayiolo-safari',
    storageBucket: 'ayiolo-safari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT9hqR2JDEq20FvA3_2bNPzGGzoJeyPf8',
    appId: '1:703908194362:ios:5f1d0426d9edae7290ed03',
    messagingSenderId: '703908194362',
    projectId: 'ayiolo-safari',
    storageBucket: 'ayiolo-safari.appspot.com',
    iosBundleId: 'com.example.ayioloSafariAdvisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT9hqR2JDEq20FvA3_2bNPzGGzoJeyPf8',
    appId: '1:703908194362:ios:151763bc0f4325d190ed03',
    messagingSenderId: '703908194362',
    projectId: 'ayiolo-safari',
    storageBucket: 'ayiolo-safari.appspot.com',
    iosBundleId: 'com.example.ayioloSafariAdvisor.RunnerTests',
  );
}
